version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    # Group related @typescript-eslint packages into one PR so plugin/parser upgrades land together
    groups:
      typescript-eslint:
        patterns:
          - "^@typescript-eslint/.*"
