name: Integration (wrangler/miniflare)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start wrangler dev (background)
        run: |
          # start wrangler dev in background on port 8787 and capture pid/logs
          nohup npx wrangler dev --local --port 8787 > wrangler.log 2>&1 &
          echo $! > wrangler.pid
          # wait for /api/auth/ping to respond (timeout ~30s)
          for i in {1..60}; do
            if curl -sSf http://localhost:8787/api/auth/ping >/dev/null 2>&1; then
              echo "wrangler ready"
              break
            fi
            sleep 0.5
          done
          if ! curl -sSf http://localhost:8787/api/auth/ping >/dev/null 2>&1; then
            echo "wrangler failed to start" >&2
            tail -n +1 wrangler.log || true
            exit 1
          fi

      - name: Run integration-check script
        env:
          BASE_URL: http://localhost:8787
        run: node scripts/integration-check.js

      - name: Tear down
        if: always()
        run: |
          if [ -f wrangler.pid ]; then
            kill "$(cat wrangler.pid)" || true
            rm -f wrangler.pid
          fi
          pkill -f 'wrangler dev' || true
          sleep 1
